In [1]:
import numpy as np

In [2]:
# arithmetic operations

In [3]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])


In [4]:
a1+a2 # all the arithmetic operations

array([ 7,  9, 11, 13, 15])

In [5]:
# broadcasting

In [6]:
l = [10,20,30,34,32]
a1 = np.array(l)
a1

array([10, 20, 30, 34, 32])

In [7]:
a1 +12

array([22, 32, 42, 46, 44])

In [8]:
# Deep and shallow copying

In [9]:
a = np.arange (1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [10]:
slice = a[:5]
slice*20


array([ 20,  40,  60,  80, 100])

In [11]:
a # no change

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [12]:
# matrix operations

In [13]:
m1 = np.arange(1,10).reshape(3,3)

m1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# matrix multip(A@B)(np.dot(A,B))

In [15]:
# transpose Array(A.T)

In [16]:
# Stacking array[np.vstack(a,b)]
# [np.hstack(a,b)] for horizontal stack where a and b are arrays
# np.column stack[a,b]


In [19]:
import numpy.char as char

In [20]:
# spiliting array 
s = np.arange(16).reshape(4,4)
s

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
import numpy as np  # Make sure numpy is imported
np.vsplit(s, 2)     # Corrected from 'vspilt' to 'vsplit'

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [31]:
import numpy as np 
a = np.hsplit(s, 4) 
a# Corrected 'hspilt' to 'hsplit' - this function splits an array horizontally into multiple sub-arrays

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [33]:
for i in a:
    print (i)

[[ 0]
 [ 4]
 [ 8]
 [12]]
[[ 1]
 [ 5]
 [ 9]
 [13]]
[[ 2]
 [ 6]
 [10]
 [14]]
[[ 3]
 [ 7]
 [11]
 [15]]
