In [6]:
import numpy as np # importing for longer time use of numpy

In [9]:
arr = np.array([1,2,3,4]) # basic array creation :Create an array.
arr

array([1, 2, 3, 4])

In [11]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr = np.arange(1,11 ) # Array  generating function : Return evenly spaced values within a given interval.
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
# generate zeros: Return a new array of given shape and type, filled with zeros.

a= np.zeros((6,6))
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
# generating ones: Return a new array of given shape and type, filled with ones.

a= np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
# linspace: Return evenly spaced numbers over a specified interval.
s= np.linspace(0,1 ,100 )
s

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [23]:
# Random number generatn:
np.random.rand(4)#Random values in a given shape.


array([0.66894492, 0.32495983, 0.30872393, 0.47575195])

In [46]:
np.random.randn(12)#Return a sample (or samples) from the "standard normal" distribution.


array([ 1.3125374 ,  0.2834465 ,  0.86236904, -0.37234731,  0.16254885,
        0.82837591,  1.24619256, -0.44514659,  0.9530576 ,  0.25471589,
        0.57827307,  1.56296449])

In [48]:
np.random.randint(10,20,30)#Return random integers from `low` (inclusive) to `high` (exclusive).


array([12, 19, 14, 11, 14, 18, 13, 10, 16, 11, 11, 15, 15, 17, 18, 10, 14,
       16, 15, 12, 11, 18, 14, 15, 18, 11, 15, 13, 11, 18])

In [52]:
# Array attributes
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
a.shape

(3, 3)

In [54]:
a.size

9

In [55]:
a.dtype

dtype('int64')

In [56]:
# Array methods
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
a.min()

np.int64(1)

In [59]:
a.max()

np.int64(9)

In [60]:
a.sum()

np.int64(45)

In [61]:
# column wise sum
np.sum(a,axis=0)

array([12, 15, 18])

In [63]:
# row wise sum
np.sum(a,axis=1)

array([ 6, 15, 24])

In [64]:
a.mean()

np.float64(5.0)

In [65]:
a.std()


np.float64(2.581988897471611)

In [67]:
# reshaping and resizing

In [72]:
a = np.arange(1,31)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
a.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])